service: kindy
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  region: ap-northeast-1
  profile: ${env:AWS_PROFILE}
  logRetentionInDays: 30
  environment:
    ACCOUNT_EMAIL: ${env:ACCOUNT_EMAIL}
    ACCOUNT_PASSWORD: ${env:ACCOUNT_PASSWORD}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

custom:
  serverless-layers:
    layersDeploymentBucket: ${cf:kindy-resouce.S3BucketForLayers}
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-prune-plugin
  - serverless-layers

package:
    patterns:
        - '!**'
        - handler.js

functions:
  crawl:
    handler: handler.crawl
    timeout: 120
    memorySize: 512
