service: kindy
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  region: ap-northeast-1
  profile: ${env:AWS_PROFILE}
  logRetentionInDays: 30
  environment:
    ACCOUNT_EMAIL: ${env:ACCOUNT_EMAIL}
    ACCOUNT_PASSWORD: ${env:ACCOUNT_PASSWORD}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

resources:
  Resources:
    LayersDeploymentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: kindy-puppeteer-layers

custom:
  serverless-layers:
    layersDeploymentBucket: kindy-puppeteer-layers
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-layers

package:
    patterns:
        - '!**'
        - handler.js

functions:
  crawl:
    handler: handler.crawl
    timeout: 120
    memorySize: 512
